name: Build & Deploy javac Documentation

on:
  workflow_dispatch:

  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-deploy:
    name: Build and Deploy javac Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build documentation
        run: |
          mvn clean
          mvn verify
          mvn javadoc:javadoc

      # TODO: Improve extraction
      - name: Extract metrics
        run: |
          mkdir -p public

          COVERAGE=$(grep -o 'Total[^%]*%' target/site/jacoco/index.html | grep -o '[0-9]\+%' | head -n1 | tr -d '%')
          TESTS=$(grep -o 'tests="[0-9]*"' target/surefire-reports/*.xml | grep -o '[0-9]*' | awk '{s+=$1} END {print s}')

          echo "{
            \"coverage\": ${COVERAGE:-0},
            \"tests\": ${TESTS:-0},
            \"status\": \"OK\"
          }" > public/metrics.json

      - name: Prepare GitHub Pages content
        run: |
          cp -r gh-pages/* public/
          cp -r target/reports/apidocs public/javadoc
          cp -r target/site/jacoco public/coverage

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public